#!/usr/bin/env node
// gvoice-login.js — ONE-TIME setup: logs into Google Voice and saves cookies
// Run this once on the phone to get authenticated cookies.
// After this, summon-server.js uses the saved cookies directly.

const puppeteer = require('puppeteer-core');
const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, 'gvoice-config.js');

async function main() {
  // Find Chromium installed by pkg
  const chromePaths = [
    '/data/data/com.termux/files/usr/bin/chromium',
    '/data/data/com.termux/files/usr/bin/chromium-browser',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
  ];
  const executablePath = chromePaths.find(p => { try { fs.accessSync(p); return true; } catch { return false; } });
  if (!executablePath) {
    console.log('Chromium not found. Install: pkg install chromium -y');
    process.exit(1);
  }

  const browser = await puppeteer.launch({
    executablePath,
    headless: false,  // Show the browser so you can log in
    args: ['--no-sandbox']
  });

  const page = await browser.newPage();
  await page.goto('https://voice.google.com', { waitUntil: 'networkidle0' });

  console.log('Please log into Google Voice in the browser window.');
  console.log('After logging in, press Enter here to save cookies...');
  await new Promise(resolve => process.stdin.once('data', resolve));

  // Extract Google cookies
  const cookies = await page.cookies();
  const important = ['__Secure-3PSID', 'SAPISID', 'SID', 'SSID', 'SIDCC', '__Secure-3PAPISID'];
  const gvCookies = {};
  for (const name of important) {
    const c = cookies.find(c => c.name === name);
    if (c) gvCookies[name] = c.value;
  }

  // Save to config file
  const config = `#!/usr/bin/env node
// Google Voice config — auto-generated by gvoice-login.js
module.exports = ${JSON.stringify(gvCookies, null, 2)};
`;
  fs.writeFileSync(CONFIG_PATH, config);
  console.log(`Cookies saved to ${CONFIG_PATH}`);
  console.log('Google cookies found:', Object.keys(gvCookies).join(', '));

  await browser.close();
}

main().catch(e => { console.error(e); process.exit(1); });
